platform :ios,      '6.0' 
pod 'FMDB'
pod 'CocoaLumberjack'
pod "PulsingHalo"
pod 'KXKiOS7ColorsAndGradients', '~> 1.0.0'
pod 'PNChart', :git => 'git://github.com/yishuiliunian/PNChart.git'
pod 'CTFeedback'
pod 'TTCounterLabel'
pod 'NSDate-TKExtensions'
pod 'TheAmazingAudioEngine'
